version: '3.8'
services:
  app: # Renomeado para "app"
    env_file:
      - ./.env
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres # Adiciona a dependência do postgres
      - kafka  # Adicione a dependência do kafka
      - redis  # Adicione a dependência do redis
    environment:
      - DB_HOST=postgres #host é igual ao nome da dependencia do db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  splunk:
    image: splunk/splunk:latest
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    volumes:
      - ./splunk-data:/opt/splunk/var/lib/splunk

volumes:
  postgres-data:
  splunk-data: