name: workflow prod
on:
    push:
        branches:
        - main
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup jdk 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: cache maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: build with maven
      run: mvn -B clean install

    - name: Run tests with coverage
      run: mvn -B test

    - name: Run tests and generate JaCoCo report
      run: mvn test jacoco:report

    - name: Verify coverage
      run: |
        COVERAGE=$(mvn jacoco:report | grep -oP '(?<=<counter type="INSTRUCTION" missed="[0-9]+" covered=")[0-9]+' | awk '{sum+=$1} END {print sum}')
        if [ "$COVERAGE" -lt 70 ]; then
          echo "Coverage is below 70%! Failing build."
          exit 1
        fi